### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Kadargo63** [Kadargo63/excelsior-inventory#1]
As a studio director, I need a mobile costume inventory management system so that I can easily access and locate costumes and info about them. I.e. sizes, amount, color etc.
* When I load app I am presented with: 
  * categories/styles (types of costumes: lyrical dresses, hip hop costumes, bottoms: shorts pants skirts) 
  * an option to "Manage Inventory": assign bin locations, change on-hand counts.
  * an option to "Edit Inventory": create, change, and delete inventory/categories.
*  When I select a category, I am presented with an inventory of images. 
* When I select an image, I am presented with all available sizes, colors, and accessories as well as working hyperlink for ordering more of each article. 
* When I select option to Manage Inventory, I am presented with inventory of bin locations.
  * I would prefer the ability to create and use QR codes to assign articles to storage bins for easy locating.
  * If QR codes are not possible, I would like at least the ability to input and edit numeric bin locations. 
  * When I select a bin location, I am presented with an adjustable inventory of items.
* When I select Edit Inventory I am given the option to:
  * add new categories/items
  * edit characteristics of existing categories/items
  * delete entire categories or items

**Comment by Kadargo63** [comment]
![image](https://user-images.githubusercontent.com/88639772/148699977-5dfd8eeb-e18c-4f85-a17d-b125d06e2976.png)

**Comment by Kadargo63** [comment]
Customer Contact Info:
Candace Isaacs
Text: 850-368-4667
Email: candaceisaacs01@gmail.com
Our website for theme inspo:
www.destinationdanceofoviedo.com

**Comment by jamwil1226** [comment]
Thanks for including all this information! Excited to get started!
